name: daily_laundry
description: "DailyLaundry â€“ your smart laundry service app"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  geocoding: ^4.0.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

